load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
  name = "spline",
  srcs = ["spline.cc"],
  hdrs = ["spline.h"],
  deps = [
  ]
)

cc_test(
  name = "spline_test",
  srcs = ["spline_test.cc"],
  deps = [
    "@gtest//:gtest_main",
  ],
)

#cc_binary(
#  name = "",
#  srcs = [""],
#  deps = [],
#)
