load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility = ["//visibility:public"])

cc_library(
  name = "angles",
  hdrs = ["angles.h"],
  srcs = ["angles.cc"],
)

cc_library(
  name = "crtp",
  hdrs = ["crtp.h"],
)